### PR TITLE
Move to FoF / beta 14 compatability

### LINKED ISSUE #11: Migration Plan to FoF Namespace
TBD.

### LINKED ISSUE #18: doorman breaks with "tr" locale
When locale is set to "tr" and doorman is activated, Flarum crashes and logs:

```
Next Symfony\Component\Translation\Exception\InvalidResourceException: Error parsing YAML, invalid file "/app/vendor/reflar/doorman/resources/locale/tr.yml" in /app/vendor/symfony/translation/Loader/YamlFileLoader.php:50
Stack trace:
#0 /app/vendor/symfony/translation/Loader/FileLoader.php(36): Symfony\Component\Translation\Loader\YamlFileLoader->loadResource('/app/vendor/ref...')
#1 /app/vendor/flarum/core/src/Locale/PrefixedYamlFileLoader.php(23): Symfony\Component\Translation\Loader\FileLoader->load('/app/vendor/ref...', 'tr', 'messages')
#2 /app/vendor/symfony/translation/Translator.php(381): Flarum\Locale\PrefixedYamlFileLoader->load(Array, 'tr', 'messages')
#3 /app/vendor/symfony/translation/Translator.php(277): Symfony\Component\Translation\Translator->doLoadCatalogue('tr')
#4 /app/vendor/symfony/translation/Translator.php(314): Symfony\Component\Translation\Translator->initializeCatalogue('tr')
#5 /app/vendor/symfony/translation/Translator.php(299): Symfony\Component\Translation\Translator->dumpCatalogue('tr', Object(Symfony\Component\Config\ConfigCache))
#6 /app/vendor/symfony/config/ConfigCacheFactory.php(46): Symfony\Component\Translation\Translator->Symfony\Component\Translation\{closure}(Object(Symfony\Component\Config\ConfigCache))
#7 /app/vendor/symfony/translation/Translator.php(300): Symfony\Component\Config\ConfigCacheFactory->cache('/app/public/../...', Object(Closure))
#8 /app/vendor/symfony/translation/Translator.php(265): Symfony\Component\Translation\Translator->initializeCacheCatalogue('tr')
#9 /app/vendor/symfony/translation/Translator.php(241): Symfony\Component\Translation\Translator->loadCatalogue('tr')
#10 /app/vendor/flarum/core/src/Locale/Translator.php(35): Symfony\Component\Translation\Translator->getCatalogue('tr')
#11 /app/vendor/symfony/translation/Translator.php(198): Flarum\Locale\Translator->getCatalogue('tr')
#12 /app/vendor/flarum/core/src/Api/Serializer/GroupSerializer.php(66): Symfony\Component\Translation\Translator->trans('core.group.admi...')
#13 /app/vendor/flarum/core/src/Api/Serializer/GroupSerializer.php(53): Flarum\Api\Serializer\GroupSerializer->translateGroupName('Admin')
```
php flarum info:
```
Flarum core 0.1.0-beta.10
PHP version: 7.2.19-0ubuntu0.18.04.2
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, sodium, session, standard, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache
+------------------------------+----------------+--------+
| Flarum Extensions            |                |        |
+------------------------------+----------------+--------+
| ID                           | Version        | Commit |
+------------------------------+----------------+--------+
| flarum-approval              | v0.1.0-beta.8  |        |
| flarum-bbcode                | v0.1.0-beta.8  |        |
| flarum-emoji                 | v0.1.0-beta.10 |        |
| flarum-flags                 | v0.1.0-beta.9  |        |
| flarum-likes                 | v0.1.0-beta.9  |        |
| flarum-lock                  | v0.1.0-beta.9  |        |
| flarum-markdown              | v0.1.0-beta.10 |        |
| flarum-mentions              | v0.1.0-beta.10 |        |
| flarum-statistics            | v0.1.0-beta.9  |        |
| flarum-sticky                | v0.1.0-beta.9  |        |
| flarum-subscriptions         | v0.1.0-beta.9  |        |
| flarum-suspend               | v0.1.0-beta.9  |        |
| flagrow-sitemap              | 0.2.0          |        |
| fof-default-user-preferences | 0.2.0          |        |
| migratetoflarum-canonical    | 0.1.0          |        |
| flarumtr-turkish-lang        | v0.1.9         |        |
| flarum-tags                  | v0.1.0-beta.10 |        |
| fof-user-bio                 | 0.1.3          |        |
| fof-reactions                | 0.1.0          |        |
| tolgaaaltas-turkish          | 0.1.10.5       |        |
| v17development-seo           | 1.0.2          |        |
| fof-secure-https             | v0.1.0         |        |
| fof-ban-ips                  | dev-master     |        |
| flarum-embed                 | v0.1.0-beta.9  |        |
| fof-transliterator           | 0.1.1          |        |
| reflar-doorman               | 0.1.4          |        |
+------------------------------+----------------+--------+
Base URL: https://ekofibilim.flarum.cloud
Installation path: /data/host/ekofibilim/app
Debug mode: off
```

### PR DESCRIPTION
**Pull request by karaok491**
- [x] Mithril 2 required changes
- [X] PHP changes
- [X] Update core version constraint
- [x] Remove non-english languages (close #18 )
- [x] Move to FoF namespace (close #11 )
- [x] Migrate settings
- [ ] Publish on packagist under FoF
- [ ] Abandon reflar package on packagist

Language pack maintainers should take note that all languages other than `en` have been removed from this extension, and the translation namespace is now `fof-doorman.*`

### CODE REVIEW

**Comment by frankli0324** [comment]
may I ask when will this be merged into master / be published?

**Comment by frankli0324** [comment]
works fine for me

**Comment by requilence** [comment]
Hello @karaok491 Can I help somehow to speed up the merge and publish to the packagist?
We depend on this extension a lot

File: js/src/admin/components/InviteCodeModal.js [hunk 1]
```diff
@@ -3,146 +3,144 @@ import Modal from 'flarum/components/Modal';
...
+                            app.translator.trans('fof-doorman.admin.modal.send')
+                        )}
+                    </div>
+                </div>
+            </div>
+        );
+    }
+
+    addEmails() {
+        this.alert = null;
```
Comment (askvortsov1) [inline js/src/admin/components/InviteCodeModal.js:90]: alertAttrs might be better naming

File: migrations/2020_11_14_000000_migrate_settings_to_fof.php [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+
+return [
+    'up' => function (Builder $schema) {
+        /**
+         * @var \Flarum\Settings\SettingsRepositoryInterface
+         */
+        $settings = app('flarum.settings');
+
+        foreach (['allowPublic'] as $setting) {
+            if ($value = $settings->get($key = "reflar.doorman.$setting")) {
```
Comment (askvortsov1) [inline migrations/2020_11_14_000000_migrate_settings_to_fof.php:24]: You could use an SQL query that replaces all strings with `reflar.doorman` with `fof.doorman`?

File: src/Api/Controllers/ListDoorkeysController.php [hunk 3]
```diff
@@ -39,7 +37,11 @@ class ListDoorkeysController extends AbstractListController
      */
     protected function data(ServerRequestInterface $request, Document $document)
     {
-        $this->assertAdmin($request->getAttribute('actor'));
+        /**
+         * @var User
+         */
+        $actor = $request->getAttribute('actor');
```
Comment (askvortsov1) [inline src/Api/Controllers/ListDoorkeysController.php:43]: This could be done in 1 line

File: src/Api/Controllers/SendInvitesController.php [hunk 4]
```diff
@@ -33,40 +43,52 @@ class SendInvitesController extends AbstractCreateController
...
+     *
+     * @return mixed
      */
     protected function data(ServerRequestInterface $request, Document $document)
     {
-        $this->assertAdmin($request->getAttribute('actor'));
+        /**
+         * @var User
+         */
+        $actor = $request->getAttribute('actor');
```
Comment (askvortsov1) [inline src/Api/Controllers/SendInvitesController.php:77]: Same here, I don't think $actor is used later.

**Review by askvortsov1 — CHANGES_REQUESTED** [review]
It would be better to remove js dist changes from the PR, and add in the github actions compilation script.

I haven't tested locally and I only looked at the stuff changed in the PR, but the stuff changed looks mostly good.

File: migrations/2020_11_14_000000_migrate_settings_to_fof.php (hunk 2 above)
Comment (karaok491) [reply migrations/2020_11_14_000000_migrate_settings_to_fof.php:24]: Agreed that it could be done this way, but this is the current president that other FoF extensions use at this time, so I'm inclined to leave this as is for now
